### ISSUE TITLE
Memory provider should return clones

### ISSUE THREAD

**Issue by 3rd-Eden** [Swaagie/dynamis#8]
The memory provider is currently returning the object that is stored in the internal database when a `get` command is issued. If you modify the contents after you've received it, it will also change it in the database. This means that we should do a `clone` of the data every single time there's a get request or do an `object.freeze` or something simular on the data that we received to prevent modifications.

I don't know which option is preferred here, discuss.

**Comment by jcrugzz** [comment]
@3rd-Eden id say a clone makes sense and provide a way to make it so you can return the reference for cases where that is ideal.

**Comment by Swaagie** [comment]
I'm fine with cloning as well, the memory overhead is minimal probably. Not sure if garbage collection might become an issue, but it shouldn't afaik.
